<<<<<<< HEAD
services:
  - type: web
    name: anime-recommender
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
=======
services:
  - type: web
    name: anime-recommender
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
>>>>>>> 0dc0ed98fd552bf57533f1028f4b5f4ec6429ec2
